### ISSUE TITLE
Prevent modification of local storage if track=false

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/roc-eln-config#5]
This options does not seem to work

Check COSY and HMBC views and some other I guess

**Comment by stropitek** [comment]
I fixed COSY, HMBC, 1H and 13 predictions

In case you encounter this problem again in another view, it's because the arguments in the constructor were wrong. The third argument should disappear and be replaced by the 4th.

Instead of 
```js
var sample = new Sample(
    data.message.couchDB, 
    data.message.uuid, 
    'sample', 
    {
        track:false
    }
);
```

it should be 
```js
var sample = new Sample(
    data.message.couchDB, 
    data.message.uuid, 
    {
        track:false
    }
);
```

**Comment by stropitek** [comment]
It would probably have been better to have `track: false` by default, but unfortunately it is not the case.

**Comment by lpatiny** [comment]
Not so many views where we change the sample so maybe we could still invert the default behaviour

**Comment by stropitek** [comment]
Ok, I'm setting the default to false
