### ISSUE TITLE
Fix calculate properties

### ISSUE THREAD

**Issue by stropitek** [cheminfo/roc-eln-config#8]
https://github.com/cheminfo/roc-eln-config/blob/a7bd5c9f20c44e44b5f0b0a977ca1d77d98a5012/configBase.js#L144-L153

This fails since the update of openchemlib in a7bd5c9f20c44e44b5f0b0a977ca1d77d98a5012

**Comment by targos** [comment]
I think you need to call new OCL.MoleculeProperties (mol)
